// <auto-generated />
using System;
using ForumAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForumAPI.Migrations
{
    [DbContext(typeof(ForumContext))]
    [Migration("20210915012339_forum")]
    partial class forum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ForumAPI.Modelos.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("ForumAPI.Modelos.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text");

                    b.Property<bool>("Solucao")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicoId");

                    b.ToTable("Resposta");
                });

            modelBuilder.Entity("ForumAPI.Modelos.Topico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Topicos");
                });

            modelBuilder.Entity("ForumAPI.Modelos.Resposta", b =>
                {
                    b.HasOne("ForumAPI.Modelos.Topico", "Topico")
                        .WithMany("Respostas")
                        .HasForeignKey("TopicoId");

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("ForumAPI.Modelos.Topico", b =>
                {
                    b.HasOne("ForumAPI.Modelos.Curso", "Curso")
                        .WithMany("Topicos")
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("ForumAPI.Modelos.Curso", b =>
                {
                    b.Navigation("Topicos");
                });

            modelBuilder.Entity("ForumAPI.Modelos.Topico", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
